---
# GROUPS
# Allows grouping of jobs together under a header and shows them on different
# tabs in the UI.
# https://concourse.ci/configuring-groups.html
groups:
  - name: tests
    jobs: [ run-unit-tests, build-artifact, run-integration-tests ]
  - name: deployment
    jobs: [ deploy-application, run-load-tests, promote-new-version ]

# RESOURCE TYPES
resource_types:

  # Artifactory
  # Implemented using Artifactory, but instead of defining a 'resource_type',
  # could instead use an established 'resource' for AWS S3, Azure Blobstore etc
  # https://github.com/pivotalservices/artifactory-resource
  - name: artifactory
    type: docker-image
    source:
      repository: pivotalservices/artifactory-resource

# RESOURCES
resources:

  # Pipeline
  # Implemented in separate repo, but could also be embedded in application
  # repo under a 'ci' directory.
  - name: pipeline-repo
    type: git
    source:
      uri: {{github-pipeline-uri}}
      branch: {{github-pipeline-branch}}

  # Application
  - name: application-repo
    type: git
    source:
      uri: {{github-application-uri}}
      branch: {{github-application-branch}}

  # Version
  # Implemented using GitHub Repository but could instead use AWS S3.
  # https://github.com/concourse/semver-resource
  - name: version
    type: semver
    source:
      initial_version: {{initial-version}}
      driver: git
      uri: {{github-version-uri}}
      branch: {{github-version-branch}}
      file: {{github-version-file}}
      username: JinpaLhawang

  # Release Candidate
  - name: release-candidate
    type: artifactory
    source:
      endpoint: {{artifactory-endpoint}}
      repository: {{artifactory-repository}}
      regex: "pcf-sb-hello-world-(?<version>.*).jar"
      username: {{artifactory-username}}
      password: {{artifactory-password}}
      skip_ssl_verification: true

  # Cloud Foundry
  # https://github.com/concourse/cf-resource
  - name: cloud-foundry
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}
      skip_cert_check: true

# JOBS
jobs:

  # TESTS

  # Run Unit Tests
  - name: run-unit-tests
    serial: true
    plan:
      # Get Application
      - get: application-repo
        trigger: true
      # Get Pipeline
      - get: pipeline-repo
        trigger: true
      # Run Unit Tests
      - task: task-run-unit-tests
        file: pipeline-repo/tasks/run-unit-tests.yml
        params:
          APPLICATION_DIR: application-repo

  # Build Artifact
  - name: build-artifact
    serial: true
    plan:
      # Get Application
      - get: application-repo
        passed: [ run-unit-tests ]
        trigger: true
      # Get Pipeline
      - get: pipeline-repo
        passed: [ run-unit-tests ]
        trigger: true
      # Determine Version Number
      - get: version
        params:
          pre: rc
      # Build Artifact
      - task: task-build-artifact
        file: pipeline-repo/tasks/build-artifact.yml
        params:
          APPLICATION_DIR: application-repo
          ARTIFACT_DIR: build
          VERSION_FILE: version/number
          ARTIFACT_ID: {{artifact-id}}
          PACKAGING: {{packaging}}
      # Put Artifact into Artifactory
      - put: release-candidate
        params:
          file: build/pcf-sb-hello-world-*.jar
      # Put Version File into S3
      - put: version
        params:
          file: version/number

  # Run Integration Tests
  - name: run-integration-tests
    serial: true
    plan:
      # Get Application
      - get: application-repo
        passed: [ build-artifact ]
        trigger: true
      # Get Pipeline
      - get: pipeline-repo
        passed: [ build-artifact ]
        trigger: true
      # Run Integration Tests
      - task: task-run-integration-tests
        file: pipeline-repo/tasks/run-integration-tests.yml
        params:
          APPLICATION_DIR: application-repo

  # DEPLOYMENT
  # Implemented using a Blue-Green Deployment Strategy
  # Runs two identical production environments called Blue and Green. At any
  # time, only one of the environments is live, with the live environment
  # serving all production traffic. Once deployed and fully tested the
  # software in not live environment, switch the router so all incoming
  # requests now go to new release.
  # https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html

  # Deploy Application to Cloud Foundry
  - name: deploy-application
    serial: true
    plan:
      # Get Application
      - get: application-repo
        passed: [ run-integration-tests ]
        trigger: true
      # Get Pipeline
      - get: pipeline-repo
        passed: [ run-integration-tests ]
        trigger: true
      # Get Version File from S3
      - get: version
        passed: [ build-artifact ]
      # Get Artifact from Artifactory
      - get: release-candidate
        passed: [ build-artifact ]
      # Get Current Blue/Green App Color
      - task: get-current-app-color
        file: pipeline-repo/tasks/get-current-app-info.yml
        params:
          CF_API: {{cf-api}}
          CF_USERNAME: {{cf-username}}
          CF_PASSWORD: {{cf-password}}
          CF_ORGANIZATION: {{cf-organization}}
          CF_SPACE: {{cf-space}}
          ARTIFACT_ID: {{artifact-id}}
      # Prepare Cloud Foundry Manifest
      - task: task-prepare-app-manifest
        file: pipeline-repo/tasks/prepare-app-manifest.yml
        params:
          APPLICATION_DIR: application-repo
          ARTIFACT_DIR: release-candidate
          OUTPUT_DIR: prepare-app-manifest
          VERSION_FILE: version/number
          ARTIFACT_ID: {{artifact-id}}
          PACKAGING: {{packaging}}
      # Deploy Application to Cloud Foundry
      - put: cloud-foundry
        params:
          manifest: prepare-app-manifest/manifest.yml

  # Run Load Tests
  - name: run-load-tests
    serial: true
    plan:
      # Get Application
      - get: application-repo
        passed: [ run-integration-tests ]
        trigger: true
      # Get Pipeline
      - get: pipeline-repo
        passed: [ deploy-application ]
        trigger: true
      # Get Current Blue/Green App Color
      - task: get-current-app-color
        file: pipeline-repo/tasks/get-current-app-info.yml
        params:
          CF_API: {{cf-api}}
          CF_USERNAME: {{cf-username}}
          CF_PASSWORD: {{cf-password}}
          CF_ORGANIZATION: {{cf-organization}}
          CF_SPACE: {{cf-space}}
          ARTIFACT_ID: {{artifact-id}}
      # Run Load Tests
      - task: run-load-tests
        file: pipeline-repo/tasks/run-load-tests.yml
        params:
          CF_APP_DOMAIN: {{cf-app-domain}}
          ARTIFACT_ID: {{artifact-id}}

  # Promote New Version
  - name: promote-new-version
    serial: true
    plan:
      # Get Application
      - get: application-repo
        passed: [ run-integration-tests ]
        trigger: true
      # Get Pipeline
      - get: pipeline-repo
        passed: [ run-load-tests ]
        trigger: true
      # Get Current Blue/Green App Color
      - task: get-current-app-color
        file: pipeline-repo/tasks/get-current-app-info.yml
        params:
          CF_API: {{cf-api}}
          CF_USERNAME: {{cf-username}}
          CF_PASSWORD: {{cf-password}}
          CF_ORGANIZATION: {{cf-organization}}
          CF_SPACE: {{cf-space}}
          ARTIFACT_ID: {{artifact-id}}
      # Switch Application Routes
      - task: switch-app-routes
        file: pipeline-repo/tasks/switch-app-routes.yml
        params:
          CF_API: {{cf-api}}
          CF_USERNAME: {{cf-username}}
          CF_PASSWORD: {{cf-password}}
          CF_ORGANIZATION: {{cf-organization}}
          CF_SPACE: {{cf-space}}
          CF_APP_DOMAIN: {{cf-app-domain}}
          ARTIFACT_ID: {{artifact-id}}
