---
# RESOURCES
resources:

  # Pipeline
  - name: pipeline-repo
    type: git
    source:
      uri: https://github.com/JinpaLhawang/pcf-sb-hello-world-pipeline.git
      branch: master

  # Application
  - name: application-repo
    type: git
    source:
      uri: https://github.com/JinpaLhawang/pcf-sb-hello-world.git
      branch: master

  # Version
  - name: version
    type: semver
    source:
      bucket: jambudvipa-pcf-sb-hello-world-releases
      initial_version: 1.0.0-rc.0
      key: current-version
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: s3.amazonaws.com

  # Release Candidate
  - name: candidate-release
    type: s3
    source:
      bucket: jambudvipa-pcf-sb-hello-world-releases
      regexp: pcf-sb-hello-world-(.*).jar
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: s3.amazonaws.com

#  # Releases
#  - name: release-bucket
#    type: s3
#    source:
#      bucket: jambudvipa-pcf-sb-hello-world-releases
#      regexp: pcf-sb-hello-world-(.*).jar
#      access_key_id: {{s3-access-key-id}}
#      secret_access_key: {{s3-secret-access-key}}
#      endpoint: s3.amazonaws.com

#  # Cloud Foundry
#  - name: resource-cf
#    type: cf
#    source:
#      api: {{cf-api}}
#      username: {{cf-username}}
#      password: {{cf-password}}
#      organization: {{cf-organization}}
#      space: {{cf-space}}
#      skip_cert_check: true

# JOBS
jobs:

  # Run Unit Tests
  - name: job-run-unit-tests
    public: true
    plan:
      # Get Pipeline
      - get: pipeline-repo
        trigger: true
      # Get Application
      - get: application-repo
        trigger: true
      # Run Unit Tests
      - task: task-run-unit-tests
        file: pipeline-repo/tasks/run-unit-tests.yml

  # Build Artifact
  - name: job-build-artifact
    serial_groups: [ version ]
    plan:
      # Get Pipeline
      - get: pipeline-repo
        passed: [ job-run-unit-tests ]
        trigger: true
      # Get Application
      - get: application-repo
        passed: [ job-run-unit-tests ]
        trigger: true
      # Determine Version Number
      - get: version
        params:
          pre: rc
      # Build Artifact
      - task: task-build-artifact
        file: pipeline-repo/tasks/build-artifact.yml
      - put: candidate-release
        params:
          file: build/pcf-sb-hello-world-*.jar
      - put: version
        params:
          file: version/number

#  # Deploy App
#  - name: job-deploy-app
#    public: true
#    serial: true
#    plan:
#      # Get Pipeline
#      - get: pipeline-repo
#      # Get App
#      - get: application-repo
#        trigger: true
#      # Run Integration Tests
#      - task: task-run-integration-tests
#        file: pipeline-repo/tasks/run-integration-tests.yml
#      # Deploy to CF
#      - put: resource-cf
#        params:
#          manifest: application-repo/manifest.yml
#          path: application-repo
