---
# RESOURCES
resources:

  # Pipeline
  - name: pipeline-repo
    type: git
    source:
      uri: {{github-pipeline-uri}}
      branch: {{github-pipeline-branch}}

  # Application
  - name: application-repo
    type: git
    source:
      uri: {{github-application-uri}}
      branch: {{github-application-branch}}

  # Version
  - name: version
    type: semver
    source:
      bucket: {{s3-bucket-version}}
      initial_version: {{initial-version}}
      key: {{s3-bucket-version-key}}
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: {{s3-endpoint}}

  # Release Candidate
  - name: release-candidate
    type: s3
    source:
      bucket: {{s3-bucket-release-candidates}}
      regexp: {{s3-bucket-release-regexp}}
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: {{s3-endpoint}}

  # Cloud Foundry
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}
      skip_cert_check: true

# JOBS
jobs:

  # Run Unit Tests
  - name: job-run-unit-tests
    public: true
    plan:
      # Get Pipeline
      - get: pipeline-repo
        trigger: true
      # Get Application
      - get: application-repo
        trigger: true
      # Run Unit Tests
      - task: task-run-unit-tests
        file: pipeline-repo/tasks/run-unit-tests.yml
        params:
          APPLICATION_DIR: application-repo

  # Build Artifact
  - name: job-build-artifact
    serial_groups: [ version ]
    plan:
      # Get Pipeline
      - get: pipeline-repo
        passed: [ job-run-unit-tests ]
        trigger: true
      # Get Application
      - get: application-repo
        passed: [ job-run-unit-tests ]
        trigger: true
      # Determine Version Number
      - get: version
        params:
          pre: rc
      # Build Artifact
      - task: task-build-artifact
        file: pipeline-repo/tasks/build-artifact.yml
        params:
          APPLICATION_DIR: application-repo
          ARTIFACT_DIR: build
          VERSION_FILE: version/number
          ARTIFACT_ID: {{artifact-id}}
          PACKAGING: {{packaging}}
      # Put Artifact into S3
      - put: release-candidate
        params:
          file: build/pcf-sb-hello-world-*.jar
      # Put Version File into S3
      - put: version
        params:
          file: version/number

  # Run Integration Tests
  - name: job-run-integration-tests
    serial: true
    plan:
      # Get Pipeline
      - get: pipeline-repo
        passed: [ job-build-artifact ]
        trigger: true
      # Get Application
      - get: application-repo
        passed: [ job-build-artifact ]
        trigger: true
      # Run Integration Tests
      - task: task-run-integration-tests
        file: pipeline-repo/tasks/run-integration-tests.yml
        params:
          APPLICATION_DIR: application-repo

  # Deploy Application to Cloud Foundry
  - name: job-deploy-application
    serial: true
    plan:
      # Get Pipeline
      - get: pipeline-repo
        passed: [ job-run-integration-tests ]
        trigger: true
      # Get Application
      - get: application-repo
        passed: [ job-run-integration-tests ]
        trigger: true
      # Get Artifact from S3
      - get: release-candidate
        passed: [ job-run-integration-tests ]
        trigger: true
      # Get Version File from S3
      - get: version
        passed: [ job-run-integration-tests ]
      # Prepare Cloud Foundry Manifest
      - task: task-prepare-app-manifest
        file: pipeline-repo/tasks/prepare-app-manifest.yml
      # Deploy Application to Cloud Foundry
      - put: cf
        params:
          manifest: prepare-app-manifest/manifest.yml
