---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: pipeline-repo
  - name: application-repo
  - name: version

outputs:
  - name: build

run:
  path: pipeline-repo/tasks/build-artifact.sh
