---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: pipeline-repo

outputs:
- name: current-app-info

run:
  path: pipeline-repo/tasks/get-current-app-info.sh
