---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sonarqube
    tag: latest

inputs:
  - name: resource-app

run:
  path: "resource-app/mvnw"
  args: [ "-f", "resource-app/pom.xml", "package", "sonar:sonar" ]

params:
  MAVEN_BASEDIR: resource-app
