---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: pipeline-repo
  - name: application-repo
  - name: release-candidate
  - name: version

outputs:
  - name: prepare-app-manifest

run:
  path: pipeline-repo/tasks/prepare-app-manifest.sh
  args: [
    --input-dir, release-candidate,
    --output-dir, prepare-app-manifest,
    --version-file, version/number,
    --input-manifest, application-repo/manifest.yml,
    --artifactId, pcf-sb-hello-world,
    --packaging, jar
  ]
