---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: pipeline-repo
  - name: application-repo
  - name: release-candidate
  - name: version

outputs:
  - name: prepare-app-manifest

run:
  path: pipeline-repo/tasks/prepare-app-manifest.sh
