---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: pipeline-repo
- name: current-app-info

run:
  path: pipeline-repo/tasks/run-load-tests.sh
